name: quickly_memo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  flutter_keyboard_visibility: ^5.4.1
  device_info_plus: ^9.1.2
  super_clipboard: ^0.8.5
  flutter_quill: ^9.1.1
  gap: ^3.0.1
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  localstore: ^1.4.0
  fluttertoast: ^8.2.6
  flutter_riverpod: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/Quickly Memo Icon Design.png'
